server:
  port: 9527
spring:
  application:
    name: gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: consumer8002
          uri: lb://consumer8002
          predicates:
            - Path=/consumer/get/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true

